- package.json
- server/config/middleware.js
- server/models/db.js
- server/models/seed.js
@csling @aaronnorby @benjaminhoffman
> finished adding data tables and seed data

- README.md
@csling @benjaminhoffman @aaronnorby
> Seed Database read me

- README.md
- client/Gruntfile.js
- client/package.json
- client/public/bundle.js
- client/public/index.html
- client/src/components/AppFrame.js
- client/src/components/ContentFrame.js
- client/src/components/NavbarFrame.js
- client/src/components/Search.js
- client/src/components/app.js
- client/src/components/content/AddOffer.js
- client/src/components/content/Auth.js
- client/src/components/content/CompanyProfile.js
- client/src/components/content/CompareCompany.js
- client/src/components/content/CompareOffer.js
- client/src/components/content/FollowCompany.js
- client/src/components/content/Home.js
- client/src/components/content/MyCompanies.js
- client/src/components/content/MyOffers.js
- client/src/components/content/Question.js
- client/src/components/content/SearchCompany.js
- client/src/components/content/UserProfile.js
- client/src/components/navbar/Tab.js
- client/src/components/navbar/Tabs.js
- server/server.js
* Creates initial client files according to Saturday's whiteboarding session
* Completes and formats the README.md to reflect new roadmap direction
* Sets up grunt
> Sets up Initial breakdown of client 

- client/Gruntfile.js
- client/package.json
- client/public/bundle.js
- client/public/index.html
- client/src/components/ContentFrame.js
- client/src/components/content/AddOffer.js
- client/src/components/content/UserProfile.js
@csling here is v1 of the AddOffer form.  a few things to note:
* i didnt use jquery.  i used XMLHttpRequest method instead, which is the raw browser object that jQ wraps around.  i will refactor into jQ tomorrow.
* i added bootstrap styling to index.html and the form
* for benefits i put healthcare and food.  we need to assign a value to those and pass to the db
> Realtime search

- server/models/offer.js
> Hot fix: change Sequelize to DataTypes to get server working again

- server/routers/apiRouter.js
- test/apiTests.js
This fix does not change any functionality, just minor cleanup.
> Fixed typo in apiTest and deleted unnecessary console log in apiRouter

- server/routers/apiRouter.js
> refactored api/offer POST

- .gitignore
- server/config/seed/seeder.js
- server/models/company.js
- server/models/index.js
> Update data seed and table

- README.md
- server/routers/data/dataRouter.js
> updated README and api logic

- README.md
- server/config/db/config.json
- server/routers/data/dataRouter.js
> added more API endpoints

- README.md
- server/backend/routers/data/dataRouter.js
@csling @aaronnorby @benjaminhoffman
> updated attach getting company data by group

- server/frontend/components/CompanyProfile.js
- server/frontend/components/UserProfile.js
- server/frontend/constants/index.js
- server/frontend/containers/ContentPage.js
- server/frontend/containers/NavBar.js
- server/package.json
> Builds out CompanyProfile functionality; adds & refactors into lodash 

- server/frontend/components/Landing.js
- server/frontend/components/Parallel.js
- server/frontend/index.js
This drastically lowers the loading time of the landing page
> Show landing chart only on button press

- server/backend/routers/apiRouter.js
> updated Offers to include company in API

- server/frontend/components/Login.js
- server/frontend/components/Signup.js
- server/public/index.html
> styled login and signup

- .gitignore
- server/frontend/components/AddOffer.js
- server/frontend/components/UserProfile.js
- server/package.json
Checks for presence of cookie before rendering Profile and MyOffers pages.
> Restrict access to Profile and MyOffers pages

- server/backend/config/middleware.js
Set cookie to NOT be httpOnly so that client can check for its presence
> Fix httpOnly problem

- server/backend/models/offer.js
- server/frontend/components/AddOffer.js
This changes the backend database. After merging this, it's a good idea to run dbreset and reseed or things might start breaking.
@csling
> Update offers input

- server/frontend/components/IndustryGraph.js
- server/frontend/components/SearchCompany.js
- server/public/index.html
- server/public/styles/industrygraph.css
- server/public/styles/main.css
I forgot to make a branch so this branch is also called redux
> graph now on search company

- server/.eslintrc
- server/frontend/components/CompanyVis.js
- server/frontend/components/IndustryGraph.js
- server/frontend/components/MyCompanies.js
- server/public/styles/industrygraph.css
You can select from the companies you follow and generate a graph comparing them
> Add Company Comparison graph

- server/frontend/components/AddOffer.js
- server/frontend/components/MyCompanies.js
- server/frontend/components/MyOffers.js
- server/frontend/components/SearchCompany.js
- server/frontend/components/UserProfile.js
- server/public/styles/main.css
@csling i haven't been about to get the offer/company remove feature to work yet.  lets pair later when you get a chance.... still need to figure out how to pass in eventhandlers.
> Styles forms & adds 'X' option to MyCompanies & MyOffers

- server/frontend/components/CompanyVis.js
- server/frontend/components/MyCompanies.js
Fix axes so a single company can be shown without collapsing chart
boundaries.
> Fix issue with visualizing one company

- server/frontend/components/MyCompanies.js
- server/frontend/components/MyOffers.js
- server/frontend/components/OfferVis.js
- server/frontend/components/UserProfile.js
- server/public/styles/industrygraph.css
Add offer value visualizations
> Feature offervalue

- server/backend/routers/authRouters/authRouter.js
- server/frontend/components/AddOffer.js
- server/frontend/components/CompanyProfile.js
- server/frontend/components/Landing.js
- server/frontend/components/Login.js
- server/frontend/components/SearchCompany.js
- server/frontend/components/Signup.js
- server/frontend/components/UserProfile.js
- server/public/index.html
@csling this works beautifully
@aaronnorby thanks for patience.  working nwo!
> Reformats Segment tracking w/ pageview & identify call

- server/frontend/components/AddOffer.js
- server/frontend/components/IndustryGraph.js
- server/frontend/components/Landing.js
- server/frontend/components/Login.js
- server/frontend/components/MyCompanies.js
- server/frontend/components/MyOffers.js
- server/frontend/components/OfferVis.js
- server/frontend/components/SearchCompany.js
- server/frontend/components/Signup.js
* updates copy on the homepage
* put login warning on searchCompany
* redirects logged in users to MyProfile
* redirects signup users to AddOffer
* handles all linter warnings
@csling @aaronnorby @csling
> Adds final cleanup changes:

- server/frontend/components/CompanyVis.js
- server/frontend/components/MyCompanies.js
- server/frontend/components/MyOffers.js
- server/frontend/components/OfferVis.js
> Fix number formatting

- server/public/index.html
We aren't using roboto anymore
> Remove script asking for google's roboto font
